import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1776998538225 implements MigrationInterface {
    name = 'InitialSchema1776998538225'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "vendors" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "company_name" character varying(200) NOT NULL, "contact_person" character varying(200), "email" character varying(255), "phone" character varying(32), "address" jsonb, "payment_terms" character varying(32) NOT NULL DEFAULT 'net30', "tax_id" character varying(64), "default_expense_account_id" uuid, "balance" numeric(18,4) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "notes" text, CONSTRAINT "PK_9c956c9797edfae5c6ddacc4e6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_417f012e92f382001c77b953c5" ON "vendors" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60091a59828d9da3aa04e42c9a" ON "vendors" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_28e6a221f093440d719d286178" ON "vendors" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "vendor_credit_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "vendor_credit_id" uuid NOT NULL, "account_id" uuid NOT NULL, "description" text NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_51d77cf242f578ea2a39661321c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89d97bd562a8b49e10b0c27b99" ON "vendor_credit_lines" ("vendor_credit_id") `);
        await queryRunner.query(`CREATE TABLE "vendor_credits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "date" date NOT NULL, "original_bill_id" uuid, "reason" text, "total" numeric(18,4) NOT NULL DEFAULT '0', "amount_applied" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "journal_entry_id" uuid, CONSTRAINT "PK_8256cae650819004f3da5714c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_699b7787f11ec05f4142a8b2de" ON "vendor_credits" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4b54f9ec529895172fe04cbd29" ON "vendor_credits" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_673b4db4e08f6b14d60f00f642" ON "vendor_credits" ("company_id", "vendor_id") `);
        await queryRunner.query(`CREATE TABLE "companies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(200) NOT NULL, "industry" character varying(100), "address" jsonb, "phone" character varying(32), "email" character varying(255), "tax_id" character varying(64), "invite_code" character varying(16) NOT NULL, "logo" text, "created_by" uuid NOT NULL, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_becae5242aa7442eabf5500e99" ON "companies" ("invite_code") `);
        await queryRunner.query(`CREATE TABLE "user_companies" ("user_id" uuid NOT NULL, "company_id" uuid NOT NULL, "role" character varying(16) NOT NULL DEFAULT 'admin', "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ca73b87c901966a9fb8960916df" PRIMARY KEY ("user_id", "company_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ca73b87c901966a9fb8960916d" ON "user_companies" ("user_id", "company_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "display_name" character varying(120) NOT NULL, "phone" character varying(32), "role" character varying(16) NOT NULL DEFAULT 'admin', "is_active" boolean NOT NULL DEFAULT true, "default_company_id" uuid, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "tax_rates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(120) NOT NULL, "rate" numeric(8,4) NOT NULL DEFAULT '0', "type" character varying(16) NOT NULL, "authority" character varying(120), "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_41164a748f3dafa373c7e508ca2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00b71664efb2afd4f76460ea2e" ON "tax_rates" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc23fd5647249c8613c2249951" ON "tax_rates" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_e552c9a5cd62ab722dc076eea9" ON "tax_rates" ("company_id", "type") `);
        await queryRunner.query(`CREATE TABLE "tax_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "tax_rate_id" uuid NOT NULL, "period" character varying(32) NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', "payment_date" date NOT NULL, "reference" character varying(64), "journal_entry_id" uuid, CONSTRAINT "PK_300678915f007d7c94439ac5dd3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e300947739a2aa1e3ad528184d" ON "tax_payments" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d65ee0f2d174067e25303cfa95" ON "tax_payments" ("company_id", "payment_date") `);
        await queryRunner.query(`CREATE TABLE "shadow_inventory_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "personnel_id" uuid NOT NULL, "item_id" uuid NOT NULL, "original_qty" numeric(18,4) NOT NULL DEFAULT '0', "current_qty" numeric(18,4) NOT NULL DEFAULT '0', "last_sync_at" TIMESTAMP WITH TIME ZONE, "sync_status" character varying(16) NOT NULL DEFAULT 'synced', CONSTRAINT "PK_d6c33c195009b66efae6c7e6c03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e05d82b33f438e7521472d2af3" ON "shadow_inventory_snapshots" ("company_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5c06256a716858718232ed539a" ON "shadow_inventory_snapshots" ("company_id", "personnel_id", "item_id") `);
        await queryRunner.query(`CREATE TABLE "company_settings" ("company_id" uuid NOT NULL, "fiscal_year_start" character varying(16) NOT NULL DEFAULT '01-01', "default_currency" character varying(8) NOT NULL DEFAULT 'PKR', "tax_id_label" character varying(32) NOT NULL DEFAULT 'NTN', "invoice_prefix" character varying(16) NOT NULL DEFAULT 'INV', "invoice_start_number" integer NOT NULL DEFAULT '1', "date_format" character varying(32) NOT NULL DEFAULT 'YYYY-MM-DD', "timezone" character varying(64) NOT NULL DEFAULT 'Asia/Karachi', "features" jsonb, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_717089d5a18a8b594c0184663ae" PRIMARY KEY ("company_id"))`);
        await queryRunner.query(`CREATE TABLE "sales_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "item_id" uuid, "description" text NOT NULL, "ordered_qty" numeric(18,4) NOT NULL DEFAULT '0', "fulfilled_qty" numeric(18,4) NOT NULL DEFAULT '0', "unit_price" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_91a9fd0ffdb8572374cf89df4da" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bea838805b97e16d358a3e11c5" ON "sales_order_lines" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "sales_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "order_number" character varying(32) NOT NULL, "order_date" date NOT NULL, "expected_date" date, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "notes" text, CONSTRAINT "PK_5328297e067ca929fbe7cf989dd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_45cf92d466ff1c66a24575ef1e" ON "sales_orders" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a1cc34a7852285b9795bae9a59" ON "sales_orders" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d75ab30e1729d861beafc038c" ON "sales_orders" ("company_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ebb809bc9eaacbbc34395150d4" ON "sales_orders" ("company_id", "order_number") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order_id" uuid NOT NULL, "item_id" uuid, "description" text NOT NULL, "ordered_qty" numeric(18,4) NOT NULL DEFAULT '0', "received_qty" numeric(18,4) NOT NULL DEFAULT '0', "unit_cost" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL DEFAULT '0', "account_id" uuid, "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_34a2082d2abb10c5d8713bc19b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d450e4816970bce0484394501" ON "purchase_order_lines" ("order_id") `);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "po_number" character varying(32) NOT NULL, "order_date" date NOT NULL, "expected_date" date, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "notes" text, CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_caed0f51e45442af8cea5c410b" ON "purchase_orders" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7abdcb602fa0ad32ecec5e7348" ON "purchase_orders" ("company_id", "vendor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_44bc0794d12f350f69f9298fe3" ON "purchase_orders" ("company_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d5a69bad90b4b215f39dc0672f" ON "purchase_orders" ("company_id", "po_number") `);
        await queryRunner.query(`CREATE TABLE "payroll_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "pay_period" character varying(64) NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "pay_date" date NOT NULL, "total_gross" numeric(18,4) NOT NULL DEFAULT '0', "total_deductions" numeric(18,4) NOT NULL DEFAULT '0', "total_net" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "journal_entry_id" uuid, "created_by" uuid NOT NULL, CONSTRAINT "PK_6049f42c972640c0eb99ba8035e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80b8c94472202fe66289580a6b" ON "payroll_runs" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dcd5494dbb23b7a401ed680eb5" ON "payroll_runs" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_43e26dcfffd83a306a33f1b515" ON "payroll_runs" ("company_id", "pay_date") `);
        await queryRunner.query(`CREATE TABLE "paystubs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payroll_run_id" uuid NOT NULL, "employee_id" uuid NOT NULL, "hours_worked" numeric(10,2) NOT NULL DEFAULT '0', "gross_pay" numeric(18,4) NOT NULL DEFAULT '0', "tax_deduction" numeric(18,4) NOT NULL DEFAULT '0', "health_insurance_deduction" numeric(18,4) NOT NULL DEFAULT '0', "retirement_deduction" numeric(18,4) NOT NULL DEFAULT '0', "other_deductions" jsonb, "net_pay" numeric(18,4) NOT NULL DEFAULT '0', "adjustments" jsonb, CONSTRAINT "PK_d0b556c507d44fabc6bc4652ba4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2296596b5110461a48eecd8b85" ON "paystubs" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_6969cc488fd1fed8055ccb259d" ON "paystubs" ("payroll_run_id") `);
        await queryRunner.query(`CREATE TABLE "payment_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "amount_applied" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_d42425dbe554ac2fd83203d6121" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_030c7f0dfde0321a0e887ce2a6" ON "payment_applications" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_26837feb7dff1906f194c00ba1" ON "payment_applications" ("payment_id") `);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "payment_date" date NOT NULL, "payment_method" character varying(32) NOT NULL, "reference" character varying(64), "amount" numeric(18,4) NOT NULL DEFAULT '0', "bank_account_id" uuid NOT NULL, "memo" text, "journal_entry_id" uuid, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4781cf05f36ba314cdd314c0c6" ON "payments" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_a874566437f9c527303b3d4ae1" ON "payments" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_b71d99698543c1db99b26cd9be" ON "payments" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "user_id" uuid NOT NULL, "type" character varying(64) NOT NULL, "title" character varying(200) NOT NULL, "message" text NOT NULL, "data" jsonb, "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c642fb845de2edcae46635863a" ON "notifications" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b510721e7df44103186f25903" ON "notifications" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_6bbcc40f36450127a500c96b04" ON "notifications" ("company_id", "user_id", "is_read") `);
        await queryRunner.query(`CREATE TABLE "general_ledger" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "date" date NOT NULL, "reference" character varying(32) NOT NULL, "account_id" uuid NOT NULL, "debit" numeric(18,4) NOT NULL DEFAULT '0', "credit" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "source_type" character varying(32) NOT NULL, "source_id" uuid NOT NULL, "memo" text, CONSTRAINT "PK_a148029e2181866d8a7fe139981" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0f90978a140629fe43f30248a7" ON "general_ledger" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_663c0de89764fd253eec45eddf" ON "general_ledger" ("company_id", "account_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_f20432d4b94925d3e5479f27ab" ON "general_ledger" ("company_id", "date") `);
        await queryRunner.query(`CREATE TABLE "journal_entry_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entry_id" uuid NOT NULL, "account_id" uuid NOT NULL, "description" text, "debit" numeric(18,4) NOT NULL DEFAULT '0', "credit" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_b2f60e3664cd9803a829fb61aa4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_aa1e0ad5bcb7f4285452182393" ON "journal_entry_lines" ("entry_id", "line_order") `);
        await queryRunner.query(`CREATE TABLE "journal_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "reference" character varying(32) NOT NULL, "date" date NOT NULL, "memo" text, "status" character varying(16) NOT NULL DEFAULT 'draft', "total_debits" numeric(18,4) NOT NULL DEFAULT '0', "total_credits" numeric(18,4) NOT NULL DEFAULT '0', "created_by" uuid NOT NULL, "posted_by" uuid, "posted_at" TIMESTAMP WITH TIME ZONE, "void_reason" text, "reversal_of_id" uuid, CONSTRAINT "PK_a70368e64230434457c8d007ab3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_435ac51210483ad504efff69a4" ON "journal_entries" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0d07201f360304fa1daf636fa" ON "journal_entries" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c242a704eaeac939630c94a9f" ON "journal_entries" ("company_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_06fbdb6d0e8183c7d6fa1937cd" ON "journal_entries" ("company_id", "reference") `);
        await queryRunner.query(`CREATE TABLE "invoice_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "description" text NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '1', "unit_price" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL DEFAULT '0', "account_id" uuid, "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_4e8ccaadaf5d0619db9d219b061" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e554609a06b180dac66a9a977c" ON "invoice_line_items" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "invoice_number" character varying(32) NOT NULL, "invoice_date" date NOT NULL, "due_date" date NOT NULL, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "discount_type" character varying(8) NOT NULL DEFAULT 'none', "discount_value" numeric(18,4) NOT NULL DEFAULT '0', "discount_amount" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "amount_paid" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "notes" text, "payment_terms" character varying(32) NOT NULL DEFAULT 'net30', "journal_entry_id" uuid, "created_by" uuid NOT NULL, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_42385e42f092f26bd38df54971" ON "invoices" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b5cc1c958b2af05283f86c60f0" ON "invoices" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_f243bae129d662d79b47ff4e67" ON "invoices" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_822d14bc3fd752a68418d755c9" ON "invoices" ("company_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c72926e1735b41a93b9c5f57c0" ON "invoices" ("company_id", "invoice_number") `);
        await queryRunner.query(`CREATE TABLE "inventory_update_request_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid NOT NULL, "item_id" uuid NOT NULL, "before_qty" numeric(18,4) NOT NULL DEFAULT '0', "delivered_qty" numeric(18,4) NOT NULL DEFAULT '0', "returned_qty" numeric(18,4) NOT NULL DEFAULT '0', "after_qty" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_3b5404149e60aa56d44452f7523" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5c762851bec654d80694127081" ON "inventory_update_request_lines" ("request_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_update_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "delivery_id" uuid NOT NULL, "personnel_id" uuid NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'pending', "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reviewed_at" TIMESTAMP WITH TIME ZONE, "reviewed_by" uuid, "approval_notes" text, "reject_reason" text, CONSTRAINT "PK_c548de21fdeac2ff27e7481d2c8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_15e63d96771c3359c13919c510" ON "inventory_update_requests" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f0b7ae2d204866c4e2498da63b" ON "inventory_update_requests" ("company_id", "submitted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_901f07f89eee9165f54be493b6" ON "inventory_update_requests" ("company_id", "personnel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_237125d36aeed8d49d2bb00916" ON "inventory_update_requests" ("company_id", "status") `);
        await queryRunner.query(`CREATE TABLE "stock_transfer_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "transfer_id" uuid NOT NULL, "item_id" uuid NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_471b427d94a3f10ca3bcd9de9ef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4133789cec434f02b9b2212a8" ON "stock_transfer_lines" ("transfer_id") `);
        await queryRunner.query(`CREATE TABLE "stock_transfers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "from_location_id" uuid, "to_location_id" uuid, "transfer_date" date NOT NULL, "reference" character varying(64), "notes" text, "status" character varying(16) NOT NULL DEFAULT 'draft', "created_by" uuid NOT NULL, CONSTRAINT "PK_ef738a3a4a578c7f1802c1bb50a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09a07ba1ad810208bb4b6b494d" ON "stock_transfers" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_54ae330f83a22677950a4126d0" ON "stock_transfers" ("company_id", "transfer_date") `);
        await queryRunner.query(`CREATE TABLE "physical_count_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "count_id" uuid NOT NULL, "item_id" uuid NOT NULL, "system_qty" numeric(18,4) NOT NULL DEFAULT '0', "counted_qty" numeric(18,4) NOT NULL DEFAULT '0', "variance" numeric(18,4) NOT NULL DEFAULT '0', "adjustment_id" uuid, CONSTRAINT "PK_37c815f191f89b07b7960ae8c52" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32ed4ed37de6eae7b947f62066" ON "physical_count_lines" ("count_id") `);
        await queryRunner.query(`CREATE TABLE "physical_counts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "count_date" date NOT NULL, "notes" text, "created_by" uuid NOT NULL, CONSTRAINT "PK_87f0a5f3fd3ffeb95f0c95d796d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9c7b295fbe906c784041aee7e0" ON "physical_counts" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d9af8565504596b4aa1981bcb4" ON "physical_counts" ("company_id", "count_date") `);
        await queryRunner.query(`CREATE TABLE "inventory_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "item_id" uuid NOT NULL, "date" date NOT NULL, "type" character varying(32) NOT NULL, "reference" character varying(64), "description" text, "quantity_change" numeric(18,4) NOT NULL DEFAULT '0', "balance_after" numeric(18,4) NOT NULL DEFAULT '0', "source_type" character varying(32), "source_id" uuid, "created_by" uuid, CONSTRAINT "PK_d7597827c1dcffae889db3ab873" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_13ec586e60dab94f52b689944e" ON "inventory_movements" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c03c38e4c29b651f8b35243699" ON "inventory_movements" ("company_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_514adcd279a6acefd9d2dc38c9" ON "inventory_movements" ("company_id", "item_id", "date") `);
        await queryRunner.query(`CREATE TABLE "inventory_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "address" jsonb, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b9591ced2c9d787495d19639575" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9d7c24623c28a067cc6bc37adb" ON "inventory_locations" ("company_id") `);
        await queryRunner.query(`CREATE TABLE "inventory_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "sku" character varying(64) NOT NULL, "name" character varying(200) NOT NULL, "description" text, "category" character varying(100), "unit_of_measure" character varying(32) NOT NULL DEFAULT 'unit', "cost_method" character varying(16) NOT NULL DEFAULT 'average', "unit_cost" numeric(18,4) NOT NULL DEFAULT '0', "selling_price" numeric(18,4) NOT NULL DEFAULT '0', "quantity_on_hand" numeric(18,4) NOT NULL DEFAULT '0', "quantity_on_order" numeric(18,4) NOT NULL DEFAULT '0', "quantity_committed" numeric(18,4) NOT NULL DEFAULT '0', "reorder_point" numeric(18,4) NOT NULL DEFAULT '0', "reorder_quantity" numeric(18,4) NOT NULL DEFAULT '0', "min_stock" numeric(18,4) NOT NULL DEFAULT '0', "max_stock" numeric(18,4) NOT NULL DEFAULT '0', "source_agency_id" uuid, "location_id" uuid, "serial_tracking" boolean NOT NULL DEFAULT false, "lot_tracking" boolean NOT NULL DEFAULT false, "barcode_data" character varying(128), "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_cf2f451407242e132547ac19169" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0941e29082b8e586c3c23eaed7" ON "inventory_items" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_93d9d66b0299322bbffb47db50" ON "inventory_items" ("company_id", "source_agency_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb39387ca5029c0ecc1ead79d2" ON "inventory_items" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7bc7f52645041834a83a220ab0" ON "inventory_items" ("company_id", "sku") `);
        await queryRunner.query(`CREATE TABLE "inventory_adjustments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "item_id" uuid NOT NULL, "date" date NOT NULL, "previous_qty" numeric(18,4) NOT NULL DEFAULT '0', "new_qty" numeric(18,4) NOT NULL DEFAULT '0', "variance" numeric(18,4) NOT NULL DEFAULT '0', "reason" character varying(32) NOT NULL, "reference_num" character varying(64), "notes" text, "journal_entry_id" uuid, "created_by" uuid NOT NULL, CONSTRAINT "PK_67a6cd67ec23f212ac3d124325e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_532db316d85f8c73813c78961e" ON "inventory_adjustments" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_300cc2bc33aafa073bfd1b6f70" ON "inventory_adjustments" ("company_id", "date") `);
        await queryRunner.query(`CREATE INDEX "IDX_35a91ebb9bfea662374ab1962d" ON "inventory_adjustments" ("company_id", "item_id") `);
        await queryRunner.query(`CREATE TABLE "estimate_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "estimate_id" uuid NOT NULL, "description" text NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '1', "unit_price" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_b1b8c9a8ec2caf90b4c1f41df87" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d2d611176987901de14f6fc1a" ON "estimate_line_items" ("estimate_id") `);
        await queryRunner.query(`CREATE TABLE "estimates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "estimate_number" character varying(32) NOT NULL, "estimate_date" date NOT NULL, "expiration_date" date, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "discount_amount" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "converted_to_invoice_id" uuid, "notes" text, CONSTRAINT "PK_447af75b2f6025adf7f80703810" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_00d8efb3dc3984bbbe17d17b88" ON "estimates" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_63333ef1916482c014259729f9" ON "estimates" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_52a81639520f3ddf9892a74b29" ON "estimates" ("company_id", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4c6d6b0c6ed17494b1b575ee08" ON "estimates" ("company_id", "estimate_number") `);
        await queryRunner.query(`CREATE TABLE "employees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "first_name" character varying(120) NOT NULL, "last_name" character varying(120) NOT NULL, "email" character varying(255), "phone" character varying(32), "department" character varying(100), "position" character varying(100), "hire_date" date, "termination_date" date, "status" character varying(16) NOT NULL DEFAULT 'active', "pay_type" character varying(16) NOT NULL DEFAULT 'salary', "salary" numeric(18,4) NOT NULL DEFAULT '0', "hourly_rate" numeric(18,4) NOT NULL DEFAULT '0', "pay_frequency" character varying(16) NOT NULL DEFAULT 'monthly', "tax_id" character varying(64), "bank_account" jsonb, "deductions" jsonb, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7f3eeef59eece4147effe7bfa6" ON "employees" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e58274cc774ba0dc1f7f966a3" ON "employees" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_26602da43c3a1b79d47a2565ba" ON "employees" ("company_id", "status") `);
        await queryRunner.query(`CREATE TABLE "delivery_personnel_profiles" ("user_id" uuid NOT NULL, "company_id" uuid NOT NULL, "vehicle_type" character varying(64), "vehicle_number" character varying(64), "zones" jsonb NOT NULL DEFAULT '[]'::jsonb, "max_load" numeric(10,2) NOT NULL DEFAULT '0', "current_load" numeric(10,2) NOT NULL DEFAULT '0', "is_available" boolean NOT NULL DEFAULT true, "status" character varying(16) NOT NULL DEFAULT 'active', "rating" numeric(3,2) NOT NULL DEFAULT '5', "total_deliveries" integer NOT NULL DEFAULT '0', "on_time_rate" numeric(5,2) NOT NULL DEFAULT '100', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a48215e28a339869434cdd9c7b" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_060c8dee26e026227ebb8e7e49" ON "delivery_personnel_profiles" ("company_id", "is_available") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c6116df2cced21354b841a24c" ON "delivery_personnel_profiles" ("company_id", "status") `);
        await queryRunner.query(`CREATE TABLE "delivery_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_id" uuid NOT NULL, "item_id" uuid NOT NULL, "ordered_qty" numeric(18,4) NOT NULL DEFAULT '0', "delivered_qty" numeric(18,4) NOT NULL DEFAULT '0', "returned_qty" numeric(18,4) NOT NULL DEFAULT '0', "unit_price" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_421035bb04c4c87c2b220e5fa8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0a526afb8ad24fb620f2c3d501" ON "delivery_items" ("delivery_id") `);
        await queryRunner.query(`CREATE TABLE "deliveries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "personnel_id" uuid, "status" character varying(16) NOT NULL DEFAULT 'unassigned', "priority" character varying(16) NOT NULL DEFAULT 'normal', "preferred_date" date, "preferred_time_slot" character varying(64), "assigned_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "notes" text, "cancel_reason" text, "created_by" uuid NOT NULL, CONSTRAINT "PK_a6ef225c5c5f0974e503bfb731f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b34ed58a2acbcb7254dad0b877" ON "deliveries" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4f6321dba41a2c8d34fd0bf20b" ON "deliveries" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae72cad29b6f10d11b06211f6f" ON "deliveries" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8735d3e81e97f5cba476f1685b" ON "deliveries" ("company_id", "personnel_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_55f8aa60b1b7ac83f6cb888a7a" ON "deliveries" ("company_id", "status") `);
        await queryRunner.query(`CREATE TABLE "delivery_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_id" uuid NOT NULL, "status" character varying(16) NOT NULL, "timestamp" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "location" jsonb, "notes" text, "changed_by" uuid NOT NULL, CONSTRAINT "PK_6d5a3b1c231e2e87c93d6a7cb44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2744237cf43a803f89226dc3d" ON "delivery_status_history" ("delivery_id", "timestamp") `);
        await queryRunner.query(`CREATE TABLE "delivery_signatures" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_id" uuid NOT NULL, "image_url" text NOT NULL, "signer_name" character varying(200), "captured_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_4c71c43384a5bc7806b5d528f2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9ac9fb22feb2e8f3ca4f014c31" ON "delivery_signatures" ("delivery_id") `);
        await queryRunner.query(`CREATE TABLE "delivery_issues" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "delivery_id" uuid NOT NULL, "issue_type" character varying(32) NOT NULL, "notes" text, "photos" jsonb NOT NULL DEFAULT '[]'::jsonb, "rescheduled" boolean NOT NULL DEFAULT false, "new_date" date, "reported_at" TIMESTAMP WITH TIME ZONE NOT NULL, "reported_by" uuid NOT NULL, CONSTRAINT "PK_f320f61ec765da2216666de7c39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e010d85e6176ced0621e3b62c1" ON "delivery_issues" ("delivery_id") `);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "company" character varying(200), "email" character varying(255), "phone" character varying(32), "billing_address" jsonb, "shipping_address" jsonb, "credit_limit" numeric(18,4) NOT NULL DEFAULT '0', "payment_terms" character varying(32) NOT NULL DEFAULT 'net30', "balance" numeric(18,4) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "notes" text, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f0e29920aaf871f3eddbea69f0" ON "customers" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fcfb5c41b2eb5a9c5bf3bb2fd" ON "customers" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_e326d4eb8b0a5e33d40d366189" ON "customers" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "credit_memo_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "credit_memo_id" uuid NOT NULL, "description" text NOT NULL, "quantity" numeric(18,4) NOT NULL DEFAULT '1', "unit_price" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "line_total" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_d75343c6e69f3ab89f2ea0f89b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3bf5b61c3ff0f4685cb7a65d45" ON "credit_memo_lines" ("credit_memo_id") `);
        await queryRunner.query(`CREATE TABLE "credit_memos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "date" date NOT NULL, "original_invoice_id" uuid, "reason" text, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "amount_applied" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "journal_entry_id" uuid, CONSTRAINT "PK_2ec6272df94e4415253a1ccc0ca" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_defe7f428656fe35ca3087dbdb" ON "credit_memos" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf154a73ad4bad37693bdda0b8" ON "credit_memos" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_80ca9319cb3c4a09e10ef25ea2" ON "credit_memos" ("company_id", "customer_id") `);
        await queryRunner.query(`CREATE TABLE "credit_memo_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "credit_memo_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', "applied_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_46eb2316dc1cca3c78d2a11f0d0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2f0de20b9129ed1a6e33d4ef0b" ON "credit_memo_applications" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b16965d8be132d635b717f2f8b" ON "credit_memo_applications" ("credit_memo_id") `);
        await queryRunner.query(`CREATE TABLE "budget_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "budget_id" uuid NOT NULL, "account_id" uuid NOT NULL, "monthly_amounts" jsonb NOT NULL, "annual_total" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_4eabf9c9d7c8edc9ad302270c94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_27df932d047b7ab0b9efd5f563" ON "budget_lines" ("budget_id") `);
        await queryRunner.query(`CREATE TABLE "budgets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "fiscal_year" integer NOT NULL, "status" character varying(16) NOT NULL DEFAULT 'draft', "total_budget" numeric(18,4) NOT NULL DEFAULT '0', "created_by" uuid NOT NULL, CONSTRAINT "PK_9c8a51748f82387644b773da482" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71cfea53b0a8c71d6556468b76" ON "budgets" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_241b6588b67375ff4a98e91edf" ON "budgets" ("company_id", "fiscal_year") `);
        await queryRunner.query(`CREATE TABLE "bill_line_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bill_id" uuid NOT NULL, "account_id" uuid NOT NULL, "description" text NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', "tax_rate" numeric(8,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "line_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_791329c8eacdb7ed615d6c13807" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_711991fa405e2ae72dfade49cb" ON "bill_line_items" ("bill_id") `);
        await queryRunner.query(`CREATE TABLE "bills" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "bill_number" character varying(64) NOT NULL, "bill_date" date NOT NULL, "due_date" date NOT NULL, "subtotal" numeric(18,4) NOT NULL DEFAULT '0', "tax_amount" numeric(18,4) NOT NULL DEFAULT '0', "total" numeric(18,4) NOT NULL DEFAULT '0', "amount_paid" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'draft', "memo" text, "journal_entry_id" uuid, CONSTRAINT "PK_a56215dfcb525755ec832cc80b7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0838387c6021623bc55f61401e" ON "bills" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_470f7d8c67a1c5adf0aa88de62" ON "bills" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a44a8819a314f811164b24a1eb" ON "bills" ("company_id", "vendor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fee2db0d606c69adb7b77a2904" ON "bills" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_886225dda647b1f3d3607f531f" ON "bills" ("company_id", "bill_number") `);
        await queryRunner.query(`CREATE TABLE "bill_payment_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bill_payment_id" uuid NOT NULL, "bill_id" uuid NOT NULL, "amount" numeric(18,4) NOT NULL DEFAULT '0', CONSTRAINT "PK_d2ee54bee9c36085182efa2bcb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_290ac52bf47a5b3aa1fe2cfaac" ON "bill_payment_applications" ("bill_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_981c1e591486e6b89718111a19" ON "bill_payment_applications" ("bill_payment_id") `);
        await queryRunner.query(`CREATE TABLE "bill_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "vendor_id" uuid NOT NULL, "bank_account_id" uuid NOT NULL, "payment_date" date NOT NULL, "payment_method" character varying(32) NOT NULL, "reference" character varying(64), "total_amount" numeric(18,4) NOT NULL DEFAULT '0', "journal_entry_id" uuid, CONSTRAINT "PK_e623f0872b8b5d875f6e3dd3af1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b6e1058b276a7dab6e957049ed" ON "bill_payments" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc91c086a12f38ccd30562e1a2" ON "bill_payments" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_688cedeba0b1aa135764d56063" ON "bill_payments" ("company_id", "vendor_id") `);
        await queryRunner.query(`CREATE TABLE "reconciliations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "bank_account_id" uuid NOT NULL, "statement_date" date NOT NULL, "statement_beginning_balance" numeric(18,4) NOT NULL DEFAULT '0', "statement_ending_balance" numeric(18,4) NOT NULL DEFAULT '0', "cleared_balance" numeric(18,4) NOT NULL DEFAULT '0', "difference" numeric(18,4) NOT NULL DEFAULT '0', "status" character varying(16) NOT NULL DEFAULT 'in_progress', "completed_at" TIMESTAMP WITH TIME ZONE, "completed_by" uuid, CONSTRAINT "PK_110f3839ca29e2fd8ff4aaec7b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a895f63f3a83d3c7bbaf2f3d6e" ON "reconciliations" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_bad956b1ce7fb5aeff39f1bf89" ON "reconciliations" ("company_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_94a9a2a93206dcc2f492df8884" ON "reconciliations" ("company_id", "bank_account_id") `);
        await queryRunner.query(`CREATE TABLE "bank_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "bank_account_id" uuid NOT NULL, "date" date NOT NULL, "type" character varying(16) NOT NULL, "payee" character varying(200), "reference" character varying(64), "amount" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "account_id" uuid, "memo" text, "is_cleared" boolean NOT NULL DEFAULT false, "cleared_date" TIMESTAMP WITH TIME ZONE, "journal_entry_id" uuid, CONSTRAINT "PK_123cc87304eefb2c497b4acdd10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fb94e591fd43168899c90eebf4" ON "bank_transactions" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_063356560ed12e84a6f352965c" ON "bank_transactions" ("company_id", "is_cleared") `);
        await queryRunner.query(`CREATE INDEX "IDX_48cbaffeb12d6692d0e4be74f1" ON "bank_transactions" ("company_id", "bank_account_id", "date") `);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "bank_name" character varying(200), "account_number" character varying(128), "account_type" character varying(32) NOT NULL DEFAULT 'checking', "balance" numeric(18,4) NOT NULL DEFAULT '0', "linked_account_id" uuid NOT NULL, "last_reconciled" TIMESTAMP WITH TIME ZONE, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c872de764f2038224a013ff25ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_869d5463de72be0afa52f0859e" ON "bank_accounts" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fc3c20dab1509f018f08e33460" ON "bank_accounts" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "password_resets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "used_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4816377aa98211c1de34469e742" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f7a4c3bc48f24df007936d217b" ON "password_resets" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_323290a9239ad3d397ad78018e" ON "password_resets" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "audit_trail" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "user_id" uuid, "action" character varying(64) NOT NULL, "module" character varying(64) NOT NULL, "resource_type" character varying(64) NOT NULL, "resource_id" uuid, "before_values" jsonb, "after_values" jsonb, "ip_address" character varying(64), "user_agent" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_91aade8e45ada93f7dc98ca7ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2b7c95349d656568c10790fbd" ON "audit_trail" ("company_id", "user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d49fed689c10684410840b3674" ON "audit_trail" ("company_id", "module", "action") `);
        await queryRunner.query(`CREATE INDEX "IDX_114c336347c9c77570553124d4" ON "audit_trail" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "agencies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "name" character varying(200) NOT NULL, "type" character varying(32) NOT NULL, "description" text, "address" jsonb, "contact" jsonb, "is_connected" boolean NOT NULL DEFAULT false, "last_sync_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_8ab1f1f53f56c8255b0d7e68b28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_282791f5cdce8907e8df04e42a" ON "agencies" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_21e9b2f612c6880b8223a8e030" ON "agencies" ("company_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "company_id" uuid NOT NULL, "account_number" character varying(20) NOT NULL, "name" character varying(150) NOT NULL, "type" character varying(20) NOT NULL, "sub_type" character varying(64) NOT NULL, "parent_id" uuid, "description" text, "opening_balance" numeric(18,4) NOT NULL DEFAULT '0', "balance" numeric(18,4) NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b22c8136b3e83352b001322480" ON "accounts" ("company_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_da064bfaf40bd126f7b8b2ad4b" ON "accounts" ("company_id", "is_active") `);
        await queryRunner.query(`CREATE INDEX "IDX_91d2149060f993ad3eca207021" ON "accounts" ("company_id", "type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_703e8b4604b6603cdcdd084544" ON "accounts" ("company_id", "account_number") `);
        await queryRunner.query(`ALTER TABLE "vendor_credit_lines" ADD CONSTRAINT "FK_89d97bd562a8b49e10b0c27b997" FOREIGN KEY ("vendor_credit_id") REFERENCES "vendor_credits"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_companies" ADD CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" ADD CONSTRAINT "FK_bea838805b97e16d358a3e11c5e" FOREIGN KEY ("order_id") REFERENCES "sales_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_6d450e4816970bce04843945015" FOREIGN KEY ("order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "paystubs" ADD CONSTRAINT "FK_6969cc488fd1fed8055ccb259d4" FOREIGN KEY ("payroll_run_id") REFERENCES "payroll_runs"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_applications" ADD CONSTRAINT "FK_26837feb7dff1906f194c00ba19" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" ADD CONSTRAINT "FK_da1a24b21015a5b635f67b5f497" FOREIGN KEY ("entry_id") REFERENCES "journal_entries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" ADD CONSTRAINT "FK_e554609a06b180dac66a9a977c5" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_update_request_lines" ADD CONSTRAINT "FK_5c762851bec654d806941270819" FOREIGN KEY ("request_id") REFERENCES "inventory_update_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" ADD CONSTRAINT "FK_f4133789cec434f02b9b2212a81" FOREIGN KEY ("transfer_id") REFERENCES "stock_transfers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_count_lines" ADD CONSTRAINT "FK_32ed4ed37de6eae7b947f620667" FOREIGN KEY ("count_id") REFERENCES "physical_counts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "estimate_line_items" ADD CONSTRAINT "FK_1d2d611176987901de14f6fc1af" FOREIGN KEY ("estimate_id") REFERENCES "estimates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "delivery_items" ADD CONSTRAINT "FK_0a526afb8ad24fb620f2c3d5014" FOREIGN KEY ("delivery_id") REFERENCES "deliveries"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_memo_lines" ADD CONSTRAINT "FK_3bf5b61c3ff0f4685cb7a65d45c" FOREIGN KEY ("credit_memo_id") REFERENCES "credit_memos"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "budget_lines" ADD CONSTRAINT "FK_27df932d047b7ab0b9efd5f5632" FOREIGN KEY ("budget_id") REFERENCES "budgets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill_line_items" ADD CONSTRAINT "FK_711991fa405e2ae72dfade49cb5" FOREIGN KEY ("bill_id") REFERENCES "bills"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bill_payment_applications" ADD CONSTRAINT "FK_981c1e591486e6b89718111a19f" FOREIGN KEY ("bill_payment_id") REFERENCES "bill_payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "bill_payment_applications" DROP CONSTRAINT "FK_981c1e591486e6b89718111a19f"`);
        await queryRunner.query(`ALTER TABLE "bill_line_items" DROP CONSTRAINT "FK_711991fa405e2ae72dfade49cb5"`);
        await queryRunner.query(`ALTER TABLE "budget_lines" DROP CONSTRAINT "FK_27df932d047b7ab0b9efd5f5632"`);
        await queryRunner.query(`ALTER TABLE "credit_memo_lines" DROP CONSTRAINT "FK_3bf5b61c3ff0f4685cb7a65d45c"`);
        await queryRunner.query(`ALTER TABLE "delivery_items" DROP CONSTRAINT "FK_0a526afb8ad24fb620f2c3d5014"`);
        await queryRunner.query(`ALTER TABLE "estimate_line_items" DROP CONSTRAINT "FK_1d2d611176987901de14f6fc1af"`);
        await queryRunner.query(`ALTER TABLE "physical_count_lines" DROP CONSTRAINT "FK_32ed4ed37de6eae7b947f620667"`);
        await queryRunner.query(`ALTER TABLE "stock_transfer_lines" DROP CONSTRAINT "FK_f4133789cec434f02b9b2212a81"`);
        await queryRunner.query(`ALTER TABLE "inventory_update_request_lines" DROP CONSTRAINT "FK_5c762851bec654d806941270819"`);
        await queryRunner.query(`ALTER TABLE "invoice_line_items" DROP CONSTRAINT "FK_e554609a06b180dac66a9a977c5"`);
        await queryRunner.query(`ALTER TABLE "journal_entry_lines" DROP CONSTRAINT "FK_da1a24b21015a5b635f67b5f497"`);
        await queryRunner.query(`ALTER TABLE "payment_applications" DROP CONSTRAINT "FK_26837feb7dff1906f194c00ba19"`);
        await queryRunner.query(`ALTER TABLE "paystubs" DROP CONSTRAINT "FK_6969cc488fd1fed8055ccb259d4"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_6d450e4816970bce04843945015"`);
        await queryRunner.query(`ALTER TABLE "sales_order_lines" DROP CONSTRAINT "FK_bea838805b97e16d358a3e11c5e"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_9e735e90e4fd3bbb4268ed96d94"`);
        await queryRunner.query(`ALTER TABLE "user_companies" DROP CONSTRAINT "FK_50c7d6aeb4ab214ad9fff29ab68"`);
        await queryRunner.query(`ALTER TABLE "vendor_credit_lines" DROP CONSTRAINT "FK_89d97bd562a8b49e10b0c27b997"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_703e8b4604b6603cdcdd084544"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91d2149060f993ad3eca207021"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da064bfaf40bd126f7b8b2ad4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b22c8136b3e83352b001322480"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_21e9b2f612c6880b8223a8e030"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_282791f5cdce8907e8df04e42a"`);
        await queryRunner.query(`DROP TABLE "agencies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_114c336347c9c77570553124d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d49fed689c10684410840b3674"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2b7c95349d656568c10790fbd"`);
        await queryRunner.query(`DROP TABLE "audit_trail"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_323290a9239ad3d397ad78018e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7a4c3bc48f24df007936d217b"`);
        await queryRunner.query(`DROP TABLE "password_resets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc3c20dab1509f018f08e33460"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_869d5463de72be0afa52f0859e"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48cbaffeb12d6692d0e4be74f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_063356560ed12e84a6f352965c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb94e591fd43168899c90eebf4"`);
        await queryRunner.query(`DROP TABLE "bank_transactions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94a9a2a93206dcc2f492df8884"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bad956b1ce7fb5aeff39f1bf89"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a895f63f3a83d3c7bbaf2f3d6e"`);
        await queryRunner.query(`DROP TABLE "reconciliations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_688cedeba0b1aa135764d56063"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc91c086a12f38ccd30562e1a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6e1058b276a7dab6e957049ed"`);
        await queryRunner.query(`DROP TABLE "bill_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_981c1e591486e6b89718111a19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_290ac52bf47a5b3aa1fe2cfaac"`);
        await queryRunner.query(`DROP TABLE "bill_payment_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_886225dda647b1f3d3607f531f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fee2db0d606c69adb7b77a2904"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a44a8819a314f811164b24a1eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_470f7d8c67a1c5adf0aa88de62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0838387c6021623bc55f61401e"`);
        await queryRunner.query(`DROP TABLE "bills"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_711991fa405e2ae72dfade49cb"`);
        await queryRunner.query(`DROP TABLE "bill_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_241b6588b67375ff4a98e91edf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71cfea53b0a8c71d6556468b76"`);
        await queryRunner.query(`DROP TABLE "budgets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27df932d047b7ab0b9efd5f563"`);
        await queryRunner.query(`DROP TABLE "budget_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b16965d8be132d635b717f2f8b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f0de20b9129ed1a6e33d4ef0b"`);
        await queryRunner.query(`DROP TABLE "credit_memo_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80ca9319cb3c4a09e10ef25ea2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf154a73ad4bad37693bdda0b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_defe7f428656fe35ca3087dbdb"`);
        await queryRunner.query(`DROP TABLE "credit_memos"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bf5b61c3ff0f4685cb7a65d45"`);
        await queryRunner.query(`DROP TABLE "credit_memo_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e326d4eb8b0a5e33d40d366189"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fcfb5c41b2eb5a9c5bf3bb2fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0e29920aaf871f3eddbea69f0"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e010d85e6176ced0621e3b62c1"`);
        await queryRunner.query(`DROP TABLE "delivery_issues"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ac9fb22feb2e8f3ca4f014c31"`);
        await queryRunner.query(`DROP TABLE "delivery_signatures"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2744237cf43a803f89226dc3d"`);
        await queryRunner.query(`DROP TABLE "delivery_status_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_55f8aa60b1b7ac83f6cb888a7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8735d3e81e97f5cba476f1685b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae72cad29b6f10d11b06211f6f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4f6321dba41a2c8d34fd0bf20b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b34ed58a2acbcb7254dad0b877"`);
        await queryRunner.query(`DROP TABLE "deliveries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a526afb8ad24fb620f2c3d501"`);
        await queryRunner.query(`DROP TABLE "delivery_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c6116df2cced21354b841a24c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_060c8dee26e026227ebb8e7e49"`);
        await queryRunner.query(`DROP TABLE "delivery_personnel_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26602da43c3a1b79d47a2565ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e58274cc774ba0dc1f7f966a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7f3eeef59eece4147effe7bfa6"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c6d6b0c6ed17494b1b575ee08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_52a81639520f3ddf9892a74b29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63333ef1916482c014259729f9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00d8efb3dc3984bbbe17d17b88"`);
        await queryRunner.query(`DROP TABLE "estimates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d2d611176987901de14f6fc1a"`);
        await queryRunner.query(`DROP TABLE "estimate_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_35a91ebb9bfea662374ab1962d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_300cc2bc33aafa073bfd1b6f70"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_532db316d85f8c73813c78961e"`);
        await queryRunner.query(`DROP TABLE "inventory_adjustments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bc7f52645041834a83a220ab0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb39387ca5029c0ecc1ead79d2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93d9d66b0299322bbffb47db50"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0941e29082b8e586c3c23eaed7"`);
        await queryRunner.query(`DROP TABLE "inventory_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9d7c24623c28a067cc6bc37adb"`);
        await queryRunner.query(`DROP TABLE "inventory_locations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_514adcd279a6acefd9d2dc38c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c03c38e4c29b651f8b35243699"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13ec586e60dab94f52b689944e"`);
        await queryRunner.query(`DROP TABLE "inventory_movements"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9af8565504596b4aa1981bcb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c7b295fbe906c784041aee7e0"`);
        await queryRunner.query(`DROP TABLE "physical_counts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32ed4ed37de6eae7b947f62066"`);
        await queryRunner.query(`DROP TABLE "physical_count_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54ae330f83a22677950a4126d0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09a07ba1ad810208bb4b6b494d"`);
        await queryRunner.query(`DROP TABLE "stock_transfers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4133789cec434f02b9b2212a8"`);
        await queryRunner.query(`DROP TABLE "stock_transfer_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_237125d36aeed8d49d2bb00916"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_901f07f89eee9165f54be493b6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f0b7ae2d204866c4e2498da63b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_15e63d96771c3359c13919c510"`);
        await queryRunner.query(`DROP TABLE "inventory_update_requests"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c762851bec654d80694127081"`);
        await queryRunner.query(`DROP TABLE "inventory_update_request_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c72926e1735b41a93b9c5f57c0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_822d14bc3fd752a68418d755c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f243bae129d662d79b47ff4e67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5cc1c958b2af05283f86c60f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_42385e42f092f26bd38df54971"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e554609a06b180dac66a9a977c"`);
        await queryRunner.query(`DROP TABLE "invoice_line_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06fbdb6d0e8183c7d6fa1937cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c242a704eaeac939630c94a9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0d07201f360304fa1daf636fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_435ac51210483ad504efff69a4"`);
        await queryRunner.query(`DROP TABLE "journal_entries"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa1e0ad5bcb7f4285452182393"`);
        await queryRunner.query(`DROP TABLE "journal_entry_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f20432d4b94925d3e5479f27ab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_663c0de89764fd253eec45eddf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f90978a140629fe43f30248a7"`);
        await queryRunner.query(`DROP TABLE "general_ledger"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bbcc40f36450127a500c96b04"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b510721e7df44103186f25903"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c642fb845de2edcae46635863a"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b71d99698543c1db99b26cd9be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a874566437f9c527303b3d4ae1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4781cf05f36ba314cdd314c0c6"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26837feb7dff1906f194c00ba1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_030c7f0dfde0321a0e887ce2a6"`);
        await queryRunner.query(`DROP TABLE "payment_applications"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6969cc488fd1fed8055ccb259d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2296596b5110461a48eecd8b85"`);
        await queryRunner.query(`DROP TABLE "paystubs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43e26dcfffd83a306a33f1b515"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcd5494dbb23b7a401ed680eb5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80b8c94472202fe66289580a6b"`);
        await queryRunner.query(`DROP TABLE "payroll_runs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5a69bad90b4b215f39dc0672f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_44bc0794d12f350f69f9298fe3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7abdcb602fa0ad32ecec5e7348"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_caed0f51e45442af8cea5c410b"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d450e4816970bce0484394501"`);
        await queryRunner.query(`DROP TABLE "purchase_order_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebb809bc9eaacbbc34395150d4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d75ab30e1729d861beafc038c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1cc34a7852285b9795bae9a59"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45cf92d466ff1c66a24575ef1e"`);
        await queryRunner.query(`DROP TABLE "sales_orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bea838805b97e16d358a3e11c5"`);
        await queryRunner.query(`DROP TABLE "sales_order_lines"`);
        await queryRunner.query(`DROP TABLE "company_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5c06256a716858718232ed539a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e05d82b33f438e7521472d2af3"`);
        await queryRunner.query(`DROP TABLE "shadow_inventory_snapshots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d65ee0f2d174067e25303cfa95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e300947739a2aa1e3ad528184d"`);
        await queryRunner.query(`DROP TABLE "tax_payments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e552c9a5cd62ab722dc076eea9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc23fd5647249c8613c2249951"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_00b71664efb2afd4f76460ea2e"`);
        await queryRunner.query(`DROP TABLE "tax_rates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca73b87c901966a9fb8960916d"`);
        await queryRunner.query(`DROP TABLE "user_companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_becae5242aa7442eabf5500e99"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_673b4db4e08f6b14d60f00f642"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4b54f9ec529895172fe04cbd29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_699b7787f11ec05f4142a8b2de"`);
        await queryRunner.query(`DROP TABLE "vendor_credits"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89d97bd562a8b49e10b0c27b99"`);
        await queryRunner.query(`DROP TABLE "vendor_credit_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28e6a221f093440d719d286178"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60091a59828d9da3aa04e42c9a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_417f012e92f382001c77b953c5"`);
        await queryRunner.query(`DROP TABLE "vendors"`);
    }

}
